import type { Metadata } from "next";
import { Darker_Grotesque, Lato, Radio_Canada_Big } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";
import { Providers } from "./providers";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400"],
});

const darkerGrotesque = Darker_Grotesque({
  variable: "--font-darker-grotesque",
  subsets: ["latin"],
});

const radioCanadaBig = Radio_Canada_Big({
  variable: "--font-radio-canada-big",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${darkerGrotesque.variable} ${radioCanadaBig.variable} antialiased bg-theme-grey-3`}
      >
        <Providers>
          <Header />
            {children}
        </Providers>
      </body>
    </html>
  );
}
